### ISSUE TITLE
Snow/Ice theamed tiles

### ISSUE THREAD

**Issue by Tom09112** [Bouncyrock/TaleSpire-Beta-AssetRequests#105]
**Describe the Asset**
Snow-covered versions of already existing tiles as well as new snow tiles. Also, new tiles that are made of ice and maybe jagged ice spikes on some others?

**Examples (images, videos, something which gets the point across**
https://dnd.wizards.com/products/tabletop-games/rpg-products/icewind-dale-rime-frostmaiden
![image](https://user-images.githubusercontent.com/67267082/85277178-e0dfe200-b47a-11ea-8e21-40fdd9bf8241.png)
![image](https://user-images.githubusercontent.com/67267082/85277194-e5a49600-b47a-11ea-9ec6-8026030f40e7.png)
![image](https://user-images.githubusercontent.com/67267082/85277212-ec330d80-b47a-11ea-874d-81d932a7bda6.png)
![image](https://user-images.githubusercontent.com/67267082/85277264-07058200-b47b-11ea-9667-ce98dc436622.png)

**Additional context**
I don't really have specific tiles in mind however as you can see from the pictures above. These are all from the new book releasing soon called Icewind Dale: Rime of the Frostmaiden. I just think tiles that could help depict a barren snow-covered wasteland and maybe even snowy versions of already existing tiles would be a cool idea. Also, this is already asking for way too much but what about a snow effect/slider that could let you have snowfall at different rates over the map? 

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Similar to #18

**Comment by USMCM1A1** [comment]
Would love this!

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106070342-93a8aa80-6104-11eb-9ce2-a40bbab39710.png)
Get ready for a frosty time, since a while we've had a few snow tiles already, and with the [latest booster pack](https://bouncyrock.com/news/articles/chilling-expedition-booster-pack) we also got a yeti to populate those snowy landscapes - there's definitely more to go, but for now this should suffice - for more concrete wishes for additions please open a new issue
