### ISSUE TITLE
More lights and subgrid position on single tile

### ISSUE THREAD

**Issue by Sendery** [Bouncyrock/TaleSpire-Beta-AssetRequests#33]
**Describe the Asset**
I do miss the capacity to place or embbed with the clipping option lights/fires/torches on walls or close to the edge of tile to be able to place the characters without stteping on the light

I suggest to get some kind of subgrid of 3x3 on each tile to place some of the lighting assets, there are some props rocks that has a 2x2 thats where i get the idea. I think that would do the trick for much of the cases using the clipping feature.

**Examples (images, videos, something which gets the point across**
In this cavern I didnt know how to set lights on the walls or really close to them to not distrub the layout
![20200509000635_1](https://user-images.githubusercontent.com/10600957/81453121-02b22d80-9189-11ea-936f-157db969b5d9.jpg)

**Additional context**
Unburden yourself of thoughts and musings here

PS: I'm sorry if my english is not good enough to get the point acroos
-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
An overhauled prop system with "subgrid" placement and more rotation angles is already planned and prototyped. Props should get "attachment points" where they can snap onto other tiles in a finer grid and get 16 different rotations to choose from.
I'll close this, because this is already in the works and not really an asset request, but more of a feature enhancement in the building system.
