### ISSUE TITLE
Minis - A few more Humanoid NPCs/PC figures (Bandits, Gnomes, Humanoids holding weapons)

### ISSUE THREAD

**Issue by dontbemadb-rad** [Bouncyrock/TaleSpire-Beta-AssetRequests#35]
**Describe the Asset**
A handful more figurines that could pull double-duty as NPCs, enemies, and heroes. They would be used to add a bit more options for players to find immersion with their own token, and a few choice ones could be repurposed for enemies or other NPCs.

I'll try and limit the list to at most 6, because I'm sure everyone wants their Half-Tiefling Necro Barbarian character or whatever, but these ones are meant to be multi-functional.

- A thief or bandit type humanoid, holding dagger or short sword (good for: bandits, thieves, rogues, town bullies, cronies, minions and PCs)
- A Gnome (good for: player race in many RPGs, forest adventures)
- A Guard, lightly armored (good for: guards, low-knights, cronies, minions, maybe PCs)
- A Generic Half Elf (good for: PCs, general Elf NPCs)
- A fit human male or female (good for: followers, helpful town-folk, rebels, tavern brawler, thug, PCs etc.)

**Examples (images, videos, something which gets the point across**

- [Bandit Example](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRSmFemTDkZw3Fi7dDn4IX2gMWjftUuB2IlqRQuhzTvoKVZnQNM&usqp=CAU)

- [Town Guard 1](http://otherworldminiatures.co.uk/figures/wp-content/uploads/2018/04/np22.jpg) or [2](https://vignette.wikia.nocookie.net/elderscrolls/images/d/dc/Lydia.png/revision/latest/scale-to-width-down/340?cb=20120906191812)

- [ Fit Human more fighter than I'd suggest](https://paizo.com/image/content/PathfinderBattles/IconicHeroes-Kess.jpg) or [maybe more like these?](https://images.dakkadakka.com/s/i/gallery/img/2019/1/22/994954.JPG)

**Additional context**
I was trying to think of figures that could be useful in a variety of settings, stories, or adventures. I'm sure there are other really good ideas not on the list, so please add who else you think would be good in a comment and we can try and stack-rank some of them?

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by lordmulgath** [comment]
+1 for the Gnome for sure!  

** ADD +1[thumbs up reaction] to give this request more attention.**

**Comment by Paul-herrera** [comment]
I'd like to push for diversity in skin tone, gender, and age.

**Comment by gupgamingtv** [comment]
I would agree with the multi functional Minis, and that miniatures will be a huge thing in getting people to play on talespire. To add to the list, Just having even one generic of other popular races. Such as have a Dragonborn in whatever generic clothing, a Furbolg in light armor and staff (druid seems to be the go to for Furbolg in 5e anyway) and def wish I could +2 for a short race gnome/halfling that would be great for NPCs and PCs as well as the above mentioned half elf.

**Comment by dontbemadb-rad** [comment]
> 
> 
> I'd like to push for diversity in skin tone, gender, and age.

I'm all for the diversity element as well, so I tried to include a few versions of people in examples. That said, I *assume* they will be adding mini-creation or importing at a later date and a I *assume* that will help with the diversity issue long term. I am proposing some of these minis as a short-term solution before GA.

**Comment by dontbemadb-rad** [comment]
> 
> 
> I would agree with the multi functional Minis, and that miniatures will be a huge thing in getting people to play on talespire. To add to the list, Just having even one generic of other popular races. Such as have a Dragonborn in whatever generic clothing, a Furbolg in light armor and staff (druid seems to be the go to for Furbolg in 5e anyway) and def wish I could +2 for a short race gnome/halfling that would be great for NPCs and PCs as well as the above mentioned half elf.

I think that's a brilliant idea. If others like it, I will modify the original list.

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106073236-f18bc100-6109-11eb-85f8-0e1be4cd4f52.png)
A variety of rogues, though admittedly only one "human" (it's actually an elf) one, the rest is merely humanoid.

![image](https://user-images.githubusercontent.com/20774976/106073329-20099c00-610a-11eb-870a-1ef69ce69e11.png)
say hello to this happy family of gnomes!

![image](https://user-images.githubusercontent.com/20774976/106075054-3533fa00-610d-11eb-9b63-2f8fc4b843be.png)
GUARDS! A bunch of other warrior minis, also in other races could also serve as guards though most of them are a bit too "heroic" to be a mere guard which is why I didn't include them here

![image](https://user-images.githubusercontent.com/20774976/106074061-82af6780-610b-11eb-80cb-ff0adac5566b.png)
A nice assortment of Half-Elves and Elves

![image](https://user-images.githubusercontent.com/20774976/106074751-b76fee80-610c-11eb-83a0-7bb7b2f86798.png)
Many commoners of many walks of life, different races and professions - I'm sure there should be one for most needs ;)

And as for dragonfolk - well, see for yourself:
![image](https://user-images.githubusercontent.com/20774976/106074957-06b61f00-610d-11eb-88a6-4c8886aff392.png)
A bit geared towards fighting and not as much "commoner", but it's a beginning

![image](https://user-images.githubusercontent.com/20774976/106075365-c905c600-610d-11eb-8b6b-a876f1bfe767.png)
And a bunch of minis for the smaller ones among us (catfolk and clockwork (machine) minis for scale)

And if that isn't enough for you, there will be a character/hero creator added to the game later down the road (work on this will begin after early access release)

I do believe this should address pretty much all of the requests, if I missed something or you wish for something else, please do tell (Consider making a new issue for the specific thing you want to add to this, as I will close this one now - if you think it is not done enough to be worth to be closed, please do tell and I'll consider opening it again)
