### ISSUE TITLE
Signage!

### ISSUE THREAD

**Issue by Benjaneer** [Bouncyrock/TaleSpire-Beta-AssetRequests#41]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
signs for street intersections and shops
it would be great if we could type something that the players could read on focus (or visually), for shops I would settle for a small selection of styles and/or symbols

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.
![s-l400](https://user-images.githubusercontent.com/9536408/81478733-00c18c00-91d4-11ea-89df-b7819696ac23.jpg)
![shop-wood-signs-260nw-54746668](https://user-images.githubusercontent.com/9536408/81478746-1b940080-91d4-11ea-8f47-102eb352af52.jpg)
![8078796-wood-signs-drawing-vector](https://user-images.githubusercontent.com/9536408/81478757-2fd7fd80-91d4-11ea-8021-c3499f7657b2.jpg)
![Medieval-Signs-Sq-k](https://user-images.githubusercontent.com/9536408/81478775-4aaa7200-91d4-11ea-977a-6c4e12e4837c.jpg)

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by flogenos** [comment]
Never even realized the game doesn't have signs. I'd use these all over the place!

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106076255-8644ed80-610f-11eb-9887-b82a2a168afd.png)
Signs!
There's definitely room for improvement with more variety, but for now I would say this should address most use cases, which is why I'll close this - if you have a specific request in addition to those, add that in a new issue for more accurate tracking :)
